spring:
  datasource:
    url: jdbc:mysql://192.168.1.201:3306/zhouyu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/views/  
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

server: 
  port:8080

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: hrj.hrj.mybitis.model  # 注意：对应实体类的路径